#!/bin/bash
#
# tildepot
# A command line tool to manage your home setup, including applications,
# dotfiles, preferences, and more.

# shellcheck source-path=../

source "$(dirname "${BASH_SOURCE[0]}")/../src/lib.sh"
source "$APP_ROOT/src/bundles.sh"
source "$APP_ROOT/src/cmd/tildepot_hook.sh"

function tildepot_usage() {
  local status="${1:-0}"
  cat <<EOS
tildepot

Manage your home setup, including applications, dotfiles, preferences, and more.
Safe for human consumption.

Usage: tildepot [command] [options]

Available Commands:
  init                $(tildepot_hook_description 'init')
  install             $(tildepot_hook_description 'install')
  update              $(tildepot_hook_description 'update')
  snapshot            $(tildepot_hook_description 'snapshot')
  diff                [TODO]
  apply               $(tildepot_hook_description 'apply')
  status              [TODO]
  git                 [TODO]
  dir                 [TODO]

Flags:
  -h, --help          Display this help message
EOS
  exit "$status"
}

function tildepot_main() {
  if [[ $# -eq 0 ]]; then
    tildepot_usage 1
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
    -h | --help | help)
      tildepot_usage
      ;;
    init | install | update | snapshot | apply)
      tildepot_hook_main "$@"
      ;;
    *)
      warn "Unrecognized option: '$1'"
      tildepot_usage 1
      ;;
    esac
  done

  exit 0
}

tildepot_main "$@"
